# Generated by Django 2.2.3 on 2019-08-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='shop',
            new_name='shops',
        ),
    ]
